---

- name: Configure vhost for domains
  template:
    src: ./templates/vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.url }}.conf"
  loop: "{{ sites }}"
  when: item.enabled
  tags: [configure-vhosts]

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ item.url }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.url }}.conf"
    state: link
  loop: "{{ sites }}"
  when: item.enabled
  notify: reload nginx
  tags: [enable-vhosts]
