---
# Add repositories and update system packages
- name: Installation install software-properties-common
  apt: name=software-properties-common
  tags: [system]

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  tags: [system]

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  tags: [system]

- name: Install system packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ os.packages }}"
  tags: [system]

- name: "Add nginx repo"
  apt_repository:
    repo: "ppa:nginx/stable"
  tags: [system]

- name: "Add Ondrej PHP repo"
  apt_repository:
    repo: "ppa:ondrej/php"
  tags: [system]
